name: Version or Publish

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: '.nvmrc'
      - name: Install packages
        run: yarn --immutable
      - name: Build library
        run: yarn build
      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
          commit: Version package
          title: Version package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
